repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.68.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_docs
      - id: terraform_tflint
      - id: terraform_validate
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
        types_or: [markdown]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
