name: 'Manage Infrastructure'
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

on:
  push:
    branches:
      - "main"
      - "dev"
    paths:
    - 'infra/**'
  pull_request:
    branches:
      - "main"
      - "dev"
    paths:
    - 'infra/**'

jobs:
  terraform:
    if: ${{ !github.event.act }} # skip during local actions testing
    name: 'TF GitHub Actions'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./infra
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Get Environment
      id: get_env
      run: |
        prod="{{ github.event.pull_request.base.ref == 'main'  || github.ref == 'refs/head/main' }}"
        if [ "$prod" = true ]; then
          echo setting infrastructure environment to prod
          echo "environment=prod" >> $GITHUB_OUTPUT
        else
          echo setting infrastructure environment to dev
          echo "environment=dev" >> $GITHUB_OUTPUT
        fi
        cat $GITHUB_OUTPUT

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::272773485930:role/custodian-272773485930-github-oidc #CONFIGURE THIS for the role created in ./modules/github-actions-iam/iam.tf
        aws-region: us-west-2 #CONFIGURE THIS
        role-duration-seconds: 900

    - name: Terraform Init
      id: init
      run: |
       echo "${{ steps.get_env.outputs.environment }}"
       terraform init \
       -backend-config="bucket=custodian-272773485930-terraform-tfstate" \
       -backend-config="key=${{ env.environment }}/terraform.tfstate" \
       -backend-config="region=us-west-2" \
       -backend-config="encrypt=true"

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      env:
        TF_ACTION_WORKING_DIR: .
      continue-on-error: true

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color -var "env=${{ env.environment }}"
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == "refs/heads/${{ env.environment }}" && github.event_name == 'push'
      run: terraform apply -auto-approve -state="${{ env.environment }}-terraform.tfstate"