name: 'processor'
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

env:
  OIDC_IAM_ROLE: arn:aws:iam::272773485930:role/custodian-272773485930-github-oidc #CONFIGURE THIS for the role created in ./modules/github-actions-iam/iam.tf
  AWS_REGION: us-west-2
  PYTHON_VERSION: 3.9.16
  SERVICE_NAME: processor
  S3_BUCKET_NAME: cloud-custodian-lambda-packages-272773485930

on:
  push:
    branches:
      - main
    paths:
      - services/processor/**
  pull_request:
    branches:
      - main
    paths:
      - services/processor/**
  
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9.16"
    - name: Build Lambda Package
      run: |
        echo "building $SERVICE_NAME lambda package(s)..."
        mkdir app
        mkdir app/build
        pip install --target app/build/python --verbose --no-cache-dir c7n --upgrade
        echo "c7n installed..."
        ls -lsta app/build/python
        cp -r services/$SERVICE_NAME/* app/build/python
        echo "lambda package contents..."
        ls -lsta app/build/python
        echo "compressing package contents..."
        zip -r app.zip app/build/python
      
    - name: Configure AWS Credentials
      if: ${{ !github.event.act }} # skip during local actions testing
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::272773485930:role/custodian-272773485930-github-oidc
        aws-region: $AWS_REGION #CONFIGURE THIS
        role-duration-seconds: 900
    
    - name: Upload Lambda Package
      run: |
        echo "Uploading $SERVICE_NAME lambda package..."
        pip install awscli
        aws s3 cp app.zip s3://$S3_BUCKET_NAME/lambda_packages/$SERVICE_NAME/app.zip --region $AWS_REGION
