name: 'Validate Cloud Custodian Policies'
permissions:
  contents: read # required to checkout the code from the repo

on:
  push:
    branches:
      - "main"
    paths:
    - services/processor/policies/**
  pull_request:
    branches:
      - "main"
    paths:
    - services/processor/policies/**
  
jobs:
  test:
    name: 'Validate c7n policies'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - name: c7n validate policies
        run:
          echo "validating c7n policies..."
          pip install c7n
          custodian validate services/processor/policies/**
