name: 'Service Versioning'
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

on:
  pull_request:
    branches:
      - "main"

jobs:
  branch_prefix:
    name: 'Check Branch Prefix'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Branch Prefix
      run: |
        BRANCH_REGEX='major|feature|bugfix'
        echo $BRANCH_REGEX
        echo ${GITHUB_REF}
        echo ${GITHUB_HEAD_REF}
        echo ${GITHUB_BASE_REF}